#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _CaDynamics_reg(void);
extern void _Ca_HVA_reg(void);
extern void _Ca_LVA_reg(void);
extern void _Ih_reg(void);
extern void _Im_reg(void);
extern void _Im_v2_reg(void);
extern void _K_P_reg(void);
extern void _K_T_reg(void);
extern void _Kd_reg(void);
extern void _Kv2like_reg(void);
extern void _Kv3_1_reg(void);
extern void _NaTa_reg(void);
extern void _NaTs_reg(void);
extern void _NaV_reg(void);
extern void _Nap_reg(void);
extern void _SK_reg(void);
extern void _cadyn_reg(void);
extern void _capool_reg(void);
extern void _cas_reg(void);
extern void _cat_reg(void);
extern void _currentclamp_reg(void);
extern void _exp2syn_stsp_reg(void);
extern void _h_reg(void);
extern void _ka_reg(void);
extern void _kaprox_reg(void);
extern void _kca_reg(void);
extern void _kdrca1_reg(void);
extern void _leak_reg(void);
extern void _na3_reg(void);
extern void _netstimNEWh_reg(void);
extern void _netstimNEWp_reg(void);
extern void _netstimNEWpud_reg(void);
extern void _sahp_reg(void);
extern void _vecevent_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," CaDynamics.mod");
    fprintf(stderr," Ca_HVA.mod");
    fprintf(stderr," Ca_LVA.mod");
    fprintf(stderr," Ih.mod");
    fprintf(stderr," Im.mod");
    fprintf(stderr," Im_v2.mod");
    fprintf(stderr," K_P.mod");
    fprintf(stderr," K_T.mod");
    fprintf(stderr," Kd.mod");
    fprintf(stderr," Kv2like.mod");
    fprintf(stderr," Kv3_1.mod");
    fprintf(stderr," NaTa.mod");
    fprintf(stderr," NaTs.mod");
    fprintf(stderr," NaV.mod");
    fprintf(stderr," Nap.mod");
    fprintf(stderr," SK.mod");
    fprintf(stderr," cadyn.mod");
    fprintf(stderr," capool.mod");
    fprintf(stderr," cas.mod");
    fprintf(stderr," cat.mod");
    fprintf(stderr," currentclamp.mod");
    fprintf(stderr," exp2syn_stsp.mod");
    fprintf(stderr," h.mod");
    fprintf(stderr," ka.mod");
    fprintf(stderr," kaprox.mod");
    fprintf(stderr," kca.mod");
    fprintf(stderr," kdrca1.mod");
    fprintf(stderr," leak.mod");
    fprintf(stderr," na3.mod");
    fprintf(stderr," netstimNEWh.mod");
    fprintf(stderr," netstimNEWp.mod");
    fprintf(stderr," netstimNEWpud.mod");
    fprintf(stderr," sahp.mod");
    fprintf(stderr," vecevent.mod");
    fprintf(stderr, "\n");
  }
  _CaDynamics_reg();
  _Ca_HVA_reg();
  _Ca_LVA_reg();
  _Ih_reg();
  _Im_reg();
  _Im_v2_reg();
  _K_P_reg();
  _K_T_reg();
  _Kd_reg();
  _Kv2like_reg();
  _Kv3_1_reg();
  _NaTa_reg();
  _NaTs_reg();
  _NaV_reg();
  _Nap_reg();
  _SK_reg();
  _cadyn_reg();
  _capool_reg();
  _cas_reg();
  _cat_reg();
  _currentclamp_reg();
  _exp2syn_stsp_reg();
  _h_reg();
  _ka_reg();
  _kaprox_reg();
  _kca_reg();
  _kdrca1_reg();
  _leak_reg();
  _na3_reg();
  _netstimNEWh_reg();
  _netstimNEWp_reg();
  _netstimNEWpud_reg();
  _sahp_reg();
  _vecevent_reg();
}
