#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/mjc6r9/envs/neuron-bmtk/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/mjc6r9/envs/neuron-bmtk/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/mjc6r9/repos/test_LUT/LUT_Prelim/biophys_components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
